package com.example.qubaatisystem.Service;

import com.example.qubaatisystem.DTO.Out.ClassroomDashboardOutDTO;
import com.example.qubaatisystem.DTO.Out.ClassroomSummaryOutDTO;
import com.example.qubaatisystem.DTO.Out.FamilyInsightOutDTO;
import com.example.qubaatisystem.DTO.Out.StudentOutDTO;
import com.example.qubaatisystem.DTO.Out.StudentProgressOutDTO;
import com.example.qubaatisystem.DTO.Out.StudentSummaryOutDTO;
import com.example.qubaatisystem.DTO.Out.TeacherDashboardActivitySummaryOutDTO;
import com.example.qubaatisystem.DTO.Out.TeacherDashboardInsightOutDTO;
import com.example.qubaatisystem.DTO.Out.TeacherDashboardMissionSummaryOutDTO;
import com.example.qubaatisystem.DTO.Out.TeacherDashboardOutDTO;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 * Produces AI-style analysis summaries.
 * When OPENAI_API_KEY is configured, text fields are generated by OpenAI (Arabic).
 * Otherwise, deterministic rule-based Arabic text is used as a fallback.
 * Numeric fields (IDs, counts, averages) always come from our backend.
 */
@Service
@RequiredArgsConstructor
public class AiAnalysisService {

    private final ClassroomService classroomService;
    private final ParentService parentService;
    private final TeacherDashboardService teacherDashboardService;
    private final OpenAiService openAiService;

    // ── System prompts ───────────────────────────────────────────────────────

    private static final String SYSTEM_PROMPT =
            "أنت مساعد تحليل تفاعلي لمنصة تعليمية سعودية مخصصة للأطفال. " +
            "مهمتك تقديم تحليل داعم ومشجع باللغة العربية، بناءً على بيانات نشاط الطالب داخل المنصة فقط. " +

            // Core safety rule — never infer academic ability from platform metrics
            "تنبيه مهم جداً: النقاط وعدد المهام المكتملة تعكس مستوى تفاعل الطالب مع المنصة حصراً، " +
            "وليست مؤشراً على مستواه الدراسي الحقيقي أو قدراته الأكاديمية. " +
            "لا تصف الطالب بأنه ضعيف أكاديمياً أو متأخر أو فاشل استناداً إلى هذه الأرقام. " +
            "إذا كانت النقاط أو المهام قليلة أو صفراً، استخدم صياغة حذرة مثل: " +
            "'لم تظهر بيانات تفاعل كافية على المنصة حتى الآن' " +
            "أو 'نشاط الطالب على المنصة ما زال في بدايته، ويُفضّل تشجيعه على استكشاف المهام'. " +

            // Tone requirements
            "اجعل الأسلوب مشجعاً وغير حكمي، مناسباً للتواصل مع الوالدين والمعلمين بشأن أطفال. " +
            "ركّز على فرص التحسين بصياغة إيجابية، وتجنب الوصم أو الأحكام القاطعة. " +

            // JSON format
            "يجب أن يكون ردّك بتنسيق JSON بالشكل التالي تمامًا بدون أي نص خارج الـ JSON: " +
            "{\"summary\": \"فقرة قصيرة تلخص مستوى التفاعل مع المنصة\", " +
            "\"strengths\": [\"نقطة إيجابية أو سلوك جيد يُشجَّع عليه\"], " +
            "\"concerns\": [\"ملاحظة حذرة وغير حكمية إن وُجدت\"], " +
            "\"recommendedActions\": [\"توصية عملية ومشجعة\"]}. " +

            // Data integrity
            "لا تخترع أرقامًا أو أسماء. استند فقط إلى البيانات المقدّمة. كن مختصراً.";

    private static final String FAMILY_SYSTEM_PROMPT =
            "أنت مساعد رؤية عائلية لمنصة تعليمية سعودية مخصصة للأطفال. " +
            "مهمتك تقديم رؤية داعمة وإيجابية للوالد حول مستوى تفاعل أبنائه مع المنصة، بناءً على البيانات المقدّمة فقط. " +

            // Core safety rule
            "تنبيه مهم جداً: النقاط وعدد المهام المكتملة تعكس نشاط الطالب على المنصة حصراً، " +
            "وليست مؤشراً على مستواه الأكاديمي أو قدراته الدراسية الحقيقية. " +
            "لا تصف أي طفل بأنه ضعيف أو متأخر أو فاشل دراسياً استناداً إلى هذه الأرقام. " +
            "إذا كانت النقاط أو المهام صفراً أو قليلة، استخدم صياغة حذرة مثل: " +
            "'لم تُسجَّل بيانات تفاعل كافية على المنصة حتى الآن' أو 'النشاط على المنصة ما زال في بدايته'. " +

            // Audience and tone
            "الجمهور المستهدف هو الوالد، وليس المعلم. اجعل الأسلوب دافئاً وأسرياً ومشجعاً. " +
            "قدّم نظرة شاملة على الأبناء كمجموعة، مع الإشارة إلى أي تباين ملحوظ بينهم إن وُجد، دون إصدار حكم. " +
            "ركّز التوصيات على ما يستطيع الوالد فعله فعلياً في البيت لدعم مشاركة أبنائه على المنصة. " +

            // JSON format
            "يجب أن يكون ردّك بتنسيق JSON بالشكل التالي تمامًا بدون أي نص خارج الـ JSON: " +
            "{\"summary\": \"فقرة قصيرة تلخص مستوى التفاعل العائلي مع المنصة\", " +
            "\"strengths\": [\"نقطة إيجابية ملحوظة على مستوى العائلة\"], " +
            "\"concerns\": [\"ملاحظة حذرة وغير حكمية عن محدودية النشاط إن وُجدت\"], " +
            "\"recommendedActions\": [\"توصية عملية ومشجعة للوالد\"]}. " +

            // Data integrity
            "لا تخترع أرقامًا أو أسماء. استند فقط إلى البيانات المقدّمة. كن مختصراً.";

    private static final String TEACHER_SYSTEM_PROMPT =
            "أنت مساعد تحليل تعليمي لمنصة سعودية مخصصة للأطفال، تخاطب معلماً. " +
            "مهمتك تقديم رؤية داعمة وعملية للمعلم حول نشاط فصوله وطلابه على المنصة (الأنشطة والمهام)، بناءً على البيانات المقدّمة فقط. " +
            "تنبيه مهم: الأرقام تعكس التفاعل مع المنصة فقط وليست حكماً على المستوى الأكاديمي الحقيقي للطلاب. " +
            "لا تصف أي طالب أو فصل بأنه ضعيف أكاديمياً. إن كانت البيانات قليلة استخدم صياغة حذرة ومشجعة. " +
            "ركّز على ما يمكن للمعلم فعله: متابعة التصحيح المعلّق، الأنشطة المتأخرة أو القريبة من الموعد، والمهارات التي تحتاج دعماً. " +
            "يجب أن يكون ردّك بتنسيق JSON بالشكل التالي تمامًا بدون أي نص خارج الـ JSON: " +
            "{\"summary\": \"فقرة قصيرة تلخص حالة فصول المعلم ونشاط الطلاب\", " +
            "\"strengths\": [\"نقطة إيجابية\"], " +
            "\"concerns\": [\"ملاحظة عملية تحتاج انتباه المعلم\"], " +
            "\"recommendedActions\": [\"إجراء عملي يقوم به المعلم\"]}. " +
            "لا تخترع أرقامًا أو أسماء. استند فقط إلى البيانات المقدّمة. كن مختصراً.";

    // ── Classroom summary ────────────────────────────────────────────────────

    public ClassroomSummaryOutDTO analyzeClassroom(Integer classroomId) {
        ClassroomDashboardOutDTO dashboard = classroomService.getDashboard(classroomId);
        List<StudentProgressOutDTO> progress = classroomService.getProgress(classroomId);

        int studentCount = progress.size();
        double avgPoints   = studentCount == 0 ? 0.0
                : progress.stream().mapToInt(StudentProgressOutDTO::getTotalPoints).average().orElse(0);
        double avgMissions = studentCount == 0 ? 0.0
                : progress.stream().mapToInt(StudentProgressOutDTO::getCompletedMissionsCount).average().orElse(0);

        // Try OpenAI for text fields
        OpenAiService.AiAnalysisResult ai = openAiService.analyze(
                SYSTEM_PROMPT,
                classroomUserPrompt(dashboard.getName(), dashboard.getTeacherName(), studentCount, avgPoints, avgMissions)
        );

        String summary;
        List<String> strengths;
        List<String> concerns;
        List<String> actions;
        String source;

        if (ai != null) {
            summary   = ai.getSummary();
            strengths = safe(ai.getStrengths());
            concerns  = safe(ai.getConcerns());
            actions   = safe(ai.getRecommendedActions());
            source    = "openai";
        } else {
            strengths = new ArrayList<>();
            concerns  = new ArrayList<>();
            actions   = new ArrayList<>();
            classroomFallback(studentCount, avgPoints, avgMissions, strengths, concerns, actions);
            summary = classroomFallbackSummary(dashboard.getName(), dashboard.getTeacherName(), studentCount, avgPoints, avgMissions);
            source  = "fallback";
        }

        return new ClassroomSummaryOutDTO(
                "تحليل الفصل: " + dashboard.getName(),
                summary, strengths, concerns, actions, now(),
                dashboard.getClassroomId(), dashboard.getName(), dashboard.getTeacherName(),
                studentCount, roundHalf(avgPoints), roundHalf(avgMissions),
                source
        );
    }

    private String classroomUserPrompt(String name, String teacher, int count, double avgPts, double avgMissions) {
        return "بيانات تفاعل الفصل مع المنصة (تعكس النشاط داخل المنصة فقط، وليس الأداء الأكاديمي):\n" +
               "- اسم الفصل: " + name + "\n" +
               "- المعلم المسؤول: " + teacher + "\n" +
               "- عدد الطلاب المسجلين في المنصة: " + count + "\n" +
               "- متوسط نقاط التفاعل على المنصة: " + round1(avgPts) + "\n" +
               "- متوسط المهام المكتملة على المنصة لكل طالب: " + round1(avgMissions) + "\n\n" +
               "قدّم تحليلاً داعماً لمستوى تفاعل الطلاب مع المنصة، وتوصيات عملية للمعلم لتشجيعهم على الاستكشاف والمشاركة. " +
               "تجنب إصدار أحكام على المستوى الدراسي الحقيقي للطلاب.";
    }

    private void classroomFallback(int count, double avgPts, double avgMissions,
                                   List<String> strengths, List<String> concerns, List<String> actions) {
        if (count == 0) {
            concerns.add("لا يوجد طلاب مسجلون حاليًا في هذا الفصل.");
            actions.add("أضف الطلاب إلى الفصل للبدء في متابعة تقدمهم.");
            return;
        }
        if (avgPts >= 70)
            strengths.add("متوسط النقاط جيد (" + round1(avgPts) + ") وهذا يدل على وجود تفاعل جيد من الطلاب.");
        else if (avgPts < 30)
            concerns.add("متوسط النقاط منخفض (" + round1(avgPts) + ")، وقد يحتاج الطلاب إلى دعم إضافي.");

        if (avgMissions >= 5)
            strengths.add("متوسط إنجاز المهام " + round1(avgMissions) + " لكل طالب، وهذا يدل على نشاط مستمر.");
        else if (avgMissions < 2)
            concerns.add("متوسط إنجاز المهام منخفض (" + round1(avgMissions) + ")، مما يدل أن الطلاب لا يتقدمون في المهام بالشكل المطلوب.");

        if (concerns.isEmpty())
            actions.add("الاستمرار على نفس الخطة مع متابعة تقدم الطلاب بشكل منتظم.");
        else
            actions.add("مراجعة المواد التعليمية وتقديم دعم موجه للطلاب الأقل تقدمًا.");
    }

    private String classroomFallbackSummary(String name, String teacher, int count, double avgPts, double avgMissions) {
        if (count == 0)
            return "الفصل '" + name + "' لا يحتوي على طلاب مسجلين حتى الآن. أضف طلابًا للبدء في متابعة التقدم.";
        String level = avgPts >= 70 ? "جيد" : avgPts >= 40 ? "متوسط" : "منخفض";
        return "الفصل '" + name + "' بإشراف المعلم " + teacher + " يحتوي على " + count
                + " طالب. الأداء العام " + level
                + " بمتوسط " + round1(avgPts) + " نقطة و" + round1(avgMissions) + " مهام مكتملة لكل طالب.";
    }

    // ── Student summary ──────────────────────────────────────────────────────

    public StudentSummaryOutDTO analyzeStudent(Integer parentId, Integer studentId) {
        // getChildOverview validates parent existence and ownership — no duplication needed.
        StudentOutDTO student = parentService.getChildOverview(parentId, studentId);

        int points   = student.getTotalPoints()            != null ? student.getTotalPoints()            : 0;
        int missions = student.getCompletedMissionsCount() != null ? student.getCompletedMissionsCount() : 0;

        OpenAiService.AiAnalysisResult ai = openAiService.analyze(
                SYSTEM_PROMPT,
                studentUserPrompt(student.getFullName(), student.getGrade(), student.getAge(),
                                  points, missions, student.getClassroomName())
        );

        String summary;
        List<String> strengths;
        List<String> concerns;
        List<String> actions;
        String source;

        if (ai != null) {
            summary   = ai.getSummary();
            strengths = safe(ai.getStrengths());
            concerns  = safe(ai.getConcerns());
            actions   = safe(ai.getRecommendedActions());
            source    = "openai";
        } else {
            strengths = new ArrayList<>();
            concerns  = new ArrayList<>();
            actions   = new ArrayList<>();
            studentFallback(points, missions, strengths, concerns, actions);
            summary = studentFallbackSummary(student.getFullName(), student.getGrade(), student.getAge(), points, missions);
            source  = "fallback";
        }

        return new StudentSummaryOutDTO(
                "ملخص تقدم الطالب: " + student.getFullName(),
                summary, strengths, concerns, actions, now(),
                parentId, student.getId(), student.getFullName(),
                student.getGrade(), student.getAge(), points, missions,
                source
        );
    }

    private String studentUserPrompt(String name, String grade, Integer age, int points, int missions, String classroomName) {
        StringBuilder sb = new StringBuilder();
        sb.append("بيانات تفاعل الطالب مع المنصة (تعكس النشاط داخل المنصة فقط، وليس المستوى الأكاديمي):\n");
        sb.append("- اسم الطالب: ").append(name).append("\n");
        sb.append("- الصف الدراسي: ").append(grade).append("\n");
        sb.append("- العمر: ").append(age).append(" سنوات\n");
        sb.append("- نقاط التفاعل المكتسبة على المنصة: ").append(points).append("\n");
        sb.append("- عدد المهام المكتملة على المنصة: ").append(missions).append("\n");
        if (classroomName != null && !classroomName.isBlank())
            sb.append("- الفصل الدراسي المسجل فيه: ").append(classroomName).append("\n");
        if (points == 0 && missions == 0)
            sb.append("\nملاحظة: لم تُسجَّل أي بيانات تفاعل للطالب على المنصة حتى الآن.\n");
        sb.append("\nقدّم تحليلاً مشجعاً ولطيفاً لمستوى تفاعل الطالب مع المنصة، وتوصيات عملية للوالد. " +
                  "تذكّر أن هذه الأرقام لا تعكس مستواه الأكاديمي الحقيقي، لذا لا تصدر أي حكم على قدراته.");
        return sb.toString();
    }

    private void studentFallback(int points, int missions,
                                 List<String> strengths, List<String> concerns, List<String> actions) {
        if (points >= 80)
            strengths.add("عدد النقاط جيد (" + points + ") ويعكس جهدًا وتفاعلًا واضحًا من الطالب.");
        else if (points < 20)
            concerns.add("عدد النقاط منخفض (" + points + ")، وقد يحتاج الطالب إلى تشجيع أو دعم إضافي.");

        if (missions >= 5)
            strengths.add("أكمل الطالب " + missions + " مهام، وهذا يدل على وجود عادات تعلم منتظمة.");
        else if (missions == 0)
            concerns.add("لم يتم إكمال أي مهام حتى الآن. يُفضّل تشجيع الطالب على البدء بالمهام التعليمية.");

        if (concerns.isEmpty())
            actions.add("الاستمرار على نفس روتين التعلم الحالي، فالطالب يسير بشكل جيد.");
        else
            actions.add("تشجيع الطالب على الدخول يوميًا وإكمال مهمة واحدة على الأقل في كل جلسة.");
    }

    private String studentFallbackSummary(String name, String grade, Integer age, int points, int missions) {
        String level = points >= 80 ? "جيد" : points >= 40 ? "متوسط" : "في البداية";
        return "الطالب " + name + " في الصف " + grade + " وعمره " + age
                + " سنوات، حصل على " + points + " نقطة وأكمل " + missions + " مهام. مستوى التقدم " + level + ".";
    }

    // ── Family dashboard insight ─────────────────────────────────────────────

    public FamilyInsightOutDTO analyzeFamilyInsight(Integer parentId) {
        // getById validates parent existence; getChildren reuses the same validation.
        var parent   = parentService.getById(parentId);
        List<StudentOutDTO> children = parentService.getChildren(parentId);

        int childCount    = children.size();
        int totalPoints   = children.stream().mapToInt(s -> s.getTotalPoints()            != null ? s.getTotalPoints()            : 0).sum();
        int totalMissions = children.stream().mapToInt(s -> s.getCompletedMissionsCount() != null ? s.getCompletedMissionsCount() : 0).sum();

        // Skip the API call if there is no data to analyse.
        OpenAiService.AiAnalysisResult ai = childCount == 0 ? null
                : openAiService.analyze(FAMILY_SYSTEM_PROMPT, familyUserPrompt(children));

        String title = "رؤية قبعتي الذكية لعائلة " + parent.getFullName();
        String summary;
        List<String> strengths;
        List<String> concerns;
        List<String> actions;
        String source;

        if (ai != null) {
            summary   = ai.getSummary();
            strengths = safe(ai.getStrengths());
            concerns  = safe(ai.getConcerns());
            actions   = safe(ai.getRecommendedActions());
            source    = "openai";
        } else {
            strengths = new ArrayList<>();
            concerns  = new ArrayList<>();
            actions   = new ArrayList<>();
            familyFallback(childCount, totalPoints, totalMissions, strengths, concerns, actions);
            summary = familyFallbackSummary(parent.getFullName(), childCount, totalPoints, totalMissions);
            source  = "fallback";
        }

        return new FamilyInsightOutDTO(
                title, summary, strengths, concerns, actions, now(), source,
                parentId, parent.getFullName(), childCount
        );
    }

    private String familyUserPrompt(List<StudentOutDTO> children) {
        StringBuilder sb = new StringBuilder();
        sb.append("بيانات تفاعل الأبناء مع المنصة (تعكس النشاط على المنصة فقط، وليس الأداء الأكاديمي):\n\n");
        sb.append("عدد الأبناء المسجلين: ").append(children.size()).append("\n\n");

        for (int i = 0; i < children.size(); i++) {
            StudentOutDTO child = children.get(i);
            int pts  = child.getTotalPoints()            != null ? child.getTotalPoints()            : 0;
            int miss = child.getCompletedMissionsCount() != null ? child.getCompletedMissionsCount() : 0;

            sb.append("الطالب ").append(i + 1).append(":\n");
            sb.append("  - الاسم: ").append(firstName(child.getFullName())).append("\n");
            sb.append("  - الصف الدراسي: ").append(child.getGrade()).append("\n");
            sb.append("  - نقاط التفاعل على المنصة: ").append(pts).append("\n");
            sb.append("  - المهام المكتملة على المنصة: ").append(miss).append("\n");
            if (child.getClassroomName() != null && !child.getClassroomName().isBlank())
                sb.append("  - الفصل الدراسي: ").append(child.getClassroomName()).append("\n");
            if (pts == 0 && miss == 0)
                sb.append("  - ملاحظة: لم تُسجَّل أي بيانات تفاعل لهذا الطالب على المنصة حتى الآن.\n");
            sb.append("\n");
        }

        sb.append("قدّم رؤية عائلية شاملة وداعمة للوالد حول مستوى تفاعل أبنائه مع المنصة، ");
        sb.append("وتوصيات عملية ومشجعة. ");
        sb.append("لا تصدر أحكاماً أكاديمية على الأبناء استناداً إلى هذه الأرقام.");
        return sb.toString();
    }

    /** Extract the first word of a full name to minimise PII sent to OpenAI. */
    private String firstName(String fullName) {
        if (fullName == null || fullName.isBlank()) return "الطالب";
        String[] parts = fullName.trim().split("\\s+");
        return parts[0];
    }

    private String familyFallbackSummary(String parentName, int count, int totalPoints, int totalMissions) {
        if (count == 0)
            return "لا يوجد أبناء مسجلون في المنصة حتى الآن. يمكنك إضافة أبنائك للبدء في متابعة تفاعلهم التعليمي.";
        if (totalMissions == 0 && totalPoints == 0)
            return "أُهلاً " + parentName + "! لم تُسجَّل بيانات تفاعل لأبنائك على المنصة حتى الآن. " +
                   "نشجّعك على دعوتهم لاستكشاف المهام التعليمية المتاحة.";
        String level = totalPoints >= count * 50 ? "جيد" : totalPoints >= count * 20 ? "متوسط" : "في بدايته";
        return "أُهلاً " + parentName + "! مستوى تفاعل أبنائك البالغ عددهم " + count
                + " مع المنصة " + level + "، بإجمالي " + totalPoints
                + " نقطة و" + totalMissions + " مهام مكتملة.";
    }

    private void familyFallback(int count, int totalPoints, int totalMissions,
                                List<String> strengths, List<String> concerns, List<String> actions) {
        if (count == 0) {
            actions.add("أضف أبناءك إلى المنصة لتبدأ في متابعة تفاعلهم التعليمي.");
            return;
        }
        if (totalMissions > count * 3)
            strengths.add("أبناؤك يُظهرون نشاطاً ملحوظاً بإكمال " + totalMissions + " مهمة على المنصة حتى الآن.");
        if (totalPoints > count * 50)
            strengths.add("إجمالي نقاط التفاعل " + totalPoints + " يعكس مشاركة جيدة من الأبناء على المنصة.");

        if (totalMissions == 0)
            concerns.add("لم تُسجَّل أي مهام مكتملة حتى الآن، مما قد يعني أن الأبناء لم يستكشفوا المنصة بعد.");
        else if (totalMissions < count * 2)
            concerns.add("مستوى التفاعل مع المهام ما زال محدوداً، ويُفضَّل تشجيع الأبناء على الاستكشاف أكثر.");

        if (concerns.isEmpty())
            actions.add("استمر في التشجيع! يمكنك متابعة تقدم كل ابن من خلال تقرير الابن التفصيلي.");
        else
            actions.add("خصّص وقتاً يومياً قصيراً لمرافقة أبنائك على المنصة وتشجيعهم على استكشاف المهام المتاحة.");
    }

    // ── Teacher dashboard insight ────────────────────────────────────────────

    public TeacherDashboardInsightOutDTO analyzeTeacherDashboard(Integer teacherId) {
        TeacherDashboardOutDTO dash = teacherDashboardService.getTeacherDashboard(teacherId);

        OpenAiService.AiAnalysisResult ai = openAiService.analyze(TEACHER_SYSTEM_PROMPT, teacherUserPrompt(dash));

        String summary;
        List<String> strengths;
        List<String> concerns;
        List<String> actions;
        String source;

        if (ai != null) {
            summary   = ai.getSummary();
            strengths = safe(ai.getStrengths());
            concerns  = safe(ai.getConcerns());
            actions   = safe(ai.getRecommendedActions());
            source    = "openai";
        } else {
            strengths = new ArrayList<>();
            concerns  = new ArrayList<>();
            actions   = new ArrayList<>();
            teacherFallback(dash, strengths, concerns, actions);
            summary = teacherFallbackSummary(dash);
            source  = "fallback";
        }

        return new TeacherDashboardInsightOutDTO(
                "رؤية لوحة المعلم: " + safeText(dash.getFullName()),
                summary, strengths, concerns, actions, now(), source,
                dash.getTeacherId(), dash.getFullName());
    }

    private String teacherUserPrompt(TeacherDashboardOutDTO d) {
        TeacherDashboardActivitySummaryOutDTO a = d.getActivitySummary();
        TeacherDashboardMissionSummaryOutDTO m = d.getMissionSummary();
        StringBuilder sb = new StringBuilder();
        sb.append("بيانات نشاط فصول المعلم على المنصة (تعكس التفاعل فقط):\n");
        sb.append("- المعلم: ").append(safeText(d.getFullName())).append("\n");
        sb.append("- عدد الفصول: ").append(nz(d.getClassroomCount())).append("\n");
        sb.append("- عدد الطلاب: ").append(nz(d.getTotalStudentCount())).append("\n");
        if (a != null) {
            sb.append("- الأنشطة التي يملكها: ").append(nz(a.getOwnedActivitiesCount()))
              .append(" (مسودة ").append(nz(a.getDraftCount()))
              .append("، بانتظار المراجعة ").append(nz(a.getPendingReviewCount()))
              .append("، معتمدة ").append(nz(a.getApprovedCount()))
              .append("، مرفوضة ").append(nz(a.getRejectedCount())).append(")\n");
            sb.append("- الأنشطة المُسندة: ").append(nz(a.getAssignedActivitiesCount())).append("\n");
            sb.append("- إجمالي التسليمات: ").append(nz(a.getSubmissionsCount()))
              .append("، بانتظار التصحيح ").append(nz(a.getPendingGradingCount()))
              .append("، مُصححة ").append(nz(a.getGradedSubmissionsCount()))
              .append("، مُعادة للطالب ").append(nz(a.getReturnedSubmissionsCount())).append("\n");
            if (a.getAverageActivityScore() != null)
                sb.append("- متوسط درجات الأنشطة: ").append(round1(a.getAverageActivityScore())).append("\n");
            sb.append("- أنشطة قريبة من الموعد: ").append(nz(a.getDueSoonAssignmentsCount()))
              .append("، أنشطة متأخرة: ").append(nz(a.getOverdueAssignmentsCount())).append("\n");
        }
        if (m != null) {
            sb.append("- مهام مكتملة لدى الطلاب: ").append(nz(m.getCompletedMissionSessionsCount())).append("\n");
            if (m.getCommonWeakSkills() != null && !m.getCommonWeakSkills().isEmpty())
                sb.append("- مهارات تحتاج دعماً: ").append(String.join("، ", m.getCommonWeakSkills())).append("\n");
        }
        sb.append("\nقدّم رؤية عملية للمعلم: نقاط القوة، وما يحتاج انتباهاً (التصحيح المعلّق/الأنشطة المتأخرة)، وإجراءات عملية. تجنّب الأحكام الأكاديمية.");
        return sb.toString();
    }

    private void teacherFallback(TeacherDashboardOutDTO d, List<String> strengths, List<String> concerns, List<String> actions) {
        TeacherDashboardActivitySummaryOutDTO a = d.getActivitySummary();
        if (nz(d.getTotalStudentCount()) == 0) {
            concerns.add("لا يوجد طلاب في فصول المعلم حتى الآن.");
            actions.add("أضف طلاباً إلى الفصول للبدء في متابعة نشاطهم.");
            return;
        }
        if (a != null) {
            if (nz(a.getApprovedCount()) > 0)
                strengths.add("لدى المعلم " + nz(a.getApprovedCount()) + " نشاطاً معتمداً جاهزاً للإسناد.");
            if (nz(a.getPendingGradingCount()) > 0)
                concerns.add("هناك " + nz(a.getPendingGradingCount()) + " تسليماً بانتظار التصحيح.");
            if (nz(a.getOverdueAssignmentsCount()) > 0)
                concerns.add("هناك " + nz(a.getOverdueAssignmentsCount()) + " نشاطاً متأخراً عن موعده.");
            if (nz(a.getPendingReviewCount()) > 0)
                concerns.add("هناك " + nz(a.getPendingReviewCount()) + " نشاطاً بانتظار المراجعة.");
        }
        if (concerns.isEmpty())
            actions.add("الاستمرار في المتابعة المنتظمة لنشاط الطلاب.");
        else
            actions.add("ابدأ بتصحيح التسليمات المعلّقة ومتابعة الأنشطة المتأخرة، ثم راجع الأنشطة المعلّقة.");
    }

    private String teacherFallbackSummary(TeacherDashboardOutDTO d) {
        TeacherDashboardActivitySummaryOutDTO a = d.getActivitySummary();
        int pending = a != null ? nz(a.getPendingGradingCount()) : 0;
        int overdue = a != null ? nz(a.getOverdueAssignmentsCount()) : 0;
        return "لدى المعلم " + safeText(d.getFullName()) + " عدد " + nz(d.getClassroomCount())
                + " فصلاً و" + nz(d.getTotalStudentCount()) + " طالباً. "
                + "التسليمات بانتظار التصحيح: " + pending + "، والأنشطة المتأخرة: " + overdue + ".";
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private int nz(Integer v) {
        return v != null ? v : 0;
    }

    private String safeText(String s) {
        return s != null ? s : "";
    }

    private List<String> safe(List<String> list) {
        return list != null ? list : new ArrayList<>();
    }

    private String round1(double val) {
        return String.format("%.1f", val);
    }

    private double roundHalf(double val) {
        return Math.round(val * 10.0) / 10.0;
    }

    private String now() {
        return LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
    }
}
