package com.example.qubaatisystem.Enum;

public enum NotificationType {
    ACTIVITY_ASSIGNED,
    ACTIVITY_DUE_SOON,
    ACTIVITY_OVERDUE,
    ACTIVITY_SUBMITTED,
    ACTIVITY_GRADED,
    ACTIVITY_RETURNED,
    SUBMISSION_REOPENED,
    TEACHER_FEEDBACK,
    MISSION_COMPLETED,
    SYSTEM_MESSAGE
}
